finalization check logic

diff --git a/snapshot_maker/mainJob.yaml b/snapshot_maker/mainJob.yaml
--- a/snapshot_maker/mainJob.yaml
+++ b/snapshot_maker/mainJob.yaml
@@ -18,24 +18,35 @@ spec:
             - "-c"
             - |
               #!/bin/sh
+
+              # Exit on any error
               set -e
 
+              # Give tezos user full ownership of mounted cache volume for writing metadata later
               sudo chown -R 100:100 /"${HISTORY_MODE}"-snapshot-cache-volume
 
+              # Set error trap in order to kill this job with the timer later
               trap "exit" SIGINT SIGTERM
 
               # Strip network from namespace
               NETWORK="${NAMESPACE%%-*}"
 
+              # Set up config for headless RPC using new restored storage
               tezos-node config init \
               --config-file /home/tezos/.tezos-node/config.json \
               --network "${NETWORK}" \
               --data-dir /var/tezos/node/data
 
+              # Run headless tezos node to validate storage on restored volume
               tezos-node run --connections 0 --config-file /home/tezos/.tezos-node/config.json --rpc-addr=127.0.0.1:8732 &
 
+              # Time validation to 2 minutes. If this takes longer then there is a tezos error
+              # and this job is tossed.
+              # Tezos does not exit on error so we have to time the job.
               sleep 2m && kill -s SIGINT 1 &
 
+              # Replace this with kubectl wait.  These loops wait on the RPC to come online and prevent log from printing same line
+              # over and over and over again.  This prints one line and waits for the RPC to come online for a clean log.
               until wget -qO-  http://localhost:8732/chains/main/blocks/head/header >/dev/null 2>&1; do
                   printf "%s Waiting for node RPC to come online.\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                   until wget -qO-  http://localhost:8732/chains/main/blocks/head/header >/dev/null 2>&1; do
@@ -45,25 +56,53 @@ spec:
                   done
               done
 
+              # If somehow we skip the above waiting loop, this kills the job if the RPC is not online.
               if ! wget -qO-  http://localhost:8732/chains/main/blocks/head/header >/dev/null 2>&1; then
                 printf "%s RPC is not online! Exiting...\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                 exit 1
+
+              # Otherwise if RPC is online, then our storage is valid and we can check if the block 
+              # is finalized and get our metadata from the RPC endpoint.
               else
                 printf "%s Node online! Storage is initialized.\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                 if [ "${HISTORY_MODE}" = archive ]; then
                   TARGET="head"
+                # Tezos devs have advised us that it is safer to target HEAD~2 for rolling artifacts.
                 else
                   HEAD_BLOCK=$(wget -qO-  http://localhost:8732/chains/main/blocks/head/header | sed -E 's/.*"hash":"?([^,"]*)"?.*/\1/')
                   TARGET="${HEAD_BLOCK}~2"
-              fi
+                fi
+
+                # Get BLOCK_HASH from RPC
                 wget -qO-  http://localhost:8732/chains/main/blocks/"${TARGET}"/header | sed -E 's/.*"hash":"?([^,"]*)"?.*/\1/' > /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_HASH
+
+                # Get BLOCK_HEIGHT from RPC
                 wget -qO-  http://localhost:8732/chains/main/blocks/head/header | sed -E 's/.*"level":"?([^,"]*)"?.*/\1/' > /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_HEIGHT
+
+
+                # We need to check if the block is finalized for archive nodes since we aren't getting
+                # validation by a Tezos snapshot like our rolling tarball. We are just zipping up the data dir from an archive node.
+                if [ "${HISTORY_MODE}" = archive ]; then
+                  # Query running node and get block
+
+                  # See if this is at least 2 blocks newer than our snapshot block.  If its not, toss this job.
+
+                  # Query running node with block level of 
+                fi
+
+                # Get BLOCK_TIMESTAMP from RPC
                 wget -qO-  http://localhost:8732/chains/main/blocks/head/header | sed -E 's/.*"timestamp":"?([^,"]*)"?.*/\1/' > /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_TIMESTAMP
+
+                # Get Tezos Version from tezos-node command
                 /usr/local/bin/tezos-node --version > /"${HISTORY_MODE}"-snapshot-cache-volume/TEZOS_VERSION
+                
+                # Print variables for debug
                 printf "%s BLOCK_HASH is...$(cat /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_HASH))\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                 printf "%s BLOCK_HEIGHT is...$(cat /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_HEIGHT)\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                 printf "%s BLOCK_TIMESTAMP is...$(cat /"${HISTORY_MODE}"-snapshot-cache-volume/BLOCK_TIMESTAMP)\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
                 printf "%s TEZOS_VERSION is...$(cat /"${HISTORY_MODE}"-snapshot-cache-volume/TEZOS_VERSION)\n" "$(date "+%Y-%m-%d %H:%M:%S" "$@")"
+
+                # Blow open permissions for next job to write to volume
                 sudo chmod -R 755 /"${HISTORY_MODE}"-snapshot-cache-volume
               fi
           volumeMounts:
